resource "aws_security_group" "tool" {
  name        = "launch-wizard-2"
  vpc_id      = "${aws_vpc.default.id}"
  description = "launch-wizard-2 created 2017-08-04T10:00:59.114+09:00"
  revoke_rules_on_delete = "false"
  tags {
    Name = "tool"
  }
}

resource "aws_security_group_rule" "tool" {
  type            = "ingress"
  from_port       = 80
  to_port         = 80
  protocol        = "tcp"
  cidr_blocks     = ["0.0.0.0/0"]
  security_group_id = "${aws_security_group.tool.id}"
}

resource "aws_security_group_rule" "tool-1" {
  type            = "ingress"
  from_port       = 8080
  to_port         = 8080
  protocol        = "tcp"
  cidr_blocks     = ["0.0.0.0/0"]
  security_group_id = "${aws_security_group.tool.id}"
}

resource "aws_security_group_rule" "tool-2" {
  type            = "ingress"
  from_port       = 22
  to_port         = 22
  protocol        = "tcp"
  cidr_blocks     = ["0.0.0.0/0"]
  security_group_id = "${aws_security_group.tool.id}"
}

resource "aws_security_group_rule" "tool-3" {
  type            = "ingress"
  from_port       = 3000
  to_port         = 3000
  protocol        = "tcp"
  cidr_blocks     = ["0.0.0.0/0"]
  security_group_id = "${aws_security_group.tool.id}"
}

resource "aws_security_group_rule" "tool-4" {
  type            = "ingress"
  from_port       = 443
  to_port         = 443
  protocol        = "tcp"
  cidr_blocks     = ["0.0.0.0/0"]
  security_group_id = "${aws_security_group.tool.id}"
}

resource "aws_security_group_rule" "tool-5" {
  type            = "egress"
  from_port       = 0
  to_port         = 0
  protocol        = "-1"
  cidr_blocks     = ["0.0.0.0/0"]
  security_group_id = "${aws_security_group.tool.id}"
}
